#!/bin/bash

# For use in || chains,
# if the exit code is -1 to -128 (aka 255 to 128), stop the || chain .
skip_errors() {
  # process.exit(n) where n is -1 to -128 should be ignored.
  # n ==   -1 => $? == 255
  # n == -128 => $? == 128
  # where n is an 8-bit signed integer
  ec=$?
  if [ "$ec" -gt 127 ] ; then
    return 0
  else
    return 1
  fi
}

# $1 exchange
# $2 market
run_alerts() {
  (
    export TA_EXCHANGE=$1
    export TA_MARKET=$2
    echo "> analyzing $TA_EXCHANGE + $TA_MARKET"

    # price relative to sma 200
    price --timeframe 2h --gt sma 200 \
      && alert --timeframe 2h "price above 2h SMA 200"
    price --timeframe 4h --gt sma 200 \
      && alert --timeframe 4h "price above 4h SMA 200"
    price --timeframe 1d --gt sma 200 \
        && alert --timeframe 1d "price above 1d SMA 200"
    price --timeframe 2h --lt sma 200 \
      && alert --timeframe 2h "price below 2h SMA 200"
    price --timeframe 4h --lt sma 200 \
      && alert --timeframe 4h "price below 4h SMA 200"
    price --timeframe 1d --lt sma 200 \
        && alert --timeframe 1d "price below 1d SMA 200"

    # sma bullish alignment
    aligned --timeframe 1h sma 50 100 200 \
      && alert --timeframe 1h "1h SMA 50 100 200 in bullish alignment"
    aligned --timeframe 4h sma 50 100 200 \
        && alert --timeframe 4h "4h SMA 50 100 200 in bullish alignment"
    aligned --timeframe 12h sma 50 100 200 \
        && alert --timeframe 12h "12h SMA 50 100 200 in bullish alignment"

    # sma bearish alignment
    aligned --timeframe 1h sma 200 100 50 \
      && alert --timeframe 1h "1h SMA 50 100 200 in bearish alignment"
    aligned --timeframe 4h sma 200 100 50 \
        && alert --timeframe 4h "4h SMA 50 100 200 in bearish alignment"
    aligned --timeframe 12h sma 200 100 50 \
        && alert --timeframe 12h "12h SMA 50 100 200 in bearish alignment"

    # golden cross
    aligned --timeframe 2h sma 50 200 \
        && alert --timeframe 2h "2h SMA golden cross"
    aligned --timeframe 4h sma 50 200 \
        && alert --timeframe 4h "4h SMA golden cross"
    aligned --timeframe 12h sma 50 200 \
        && alert --timeframe 12h "12h SMA golden cross"
    aligned --timeframe 1d sma 50 200 \
        && alert --timeframe 1d "1d SMA golden cross"

    # death cross
    aligned --timeframe 2h sma 200 50 \
        && alert --timeframe 2h "2h SMA death cross"
    aligned --timeframe 4h sma 200 50 \
        && alert --timeframe 4h "4h SMA death cross"
    aligned --timeframe 12h sma 200 50 \
        && alert --timeframe 12h "12h SMA death cross"
    aligned --timeframe 1d sma 200 50 \
        && alert --timeframe 1d "1d SMA death cross"

    # divergence --bullish --timeframe 1d
    # divergence --bullish --timeframe 4h
    # divergence --bearish --timeframe 1d
    # divergence --bearish --timeframe 4h
  )
}

run_extra_alerts() {
    [ -e extra.sh ] && source extra.sh
}

run_all_alerts() {
  for market in $(cat markets) ; do
    run_alerts binance $market
  done
  run_extra_alerts
}

# Run periodically
echo "> starting alerts"
run_all_alertswhile sleep 300 ; do
  run_all_alerts
done
