#!/bin/bash

source lib.sh

# $1 exchange
# $2 market
run_alerts() {
  (
    export TA_EXCHANGE=$1
    export TA_MARKET=$2
    export ALERT_BULLISH_PRICE=${ALERT_BULLISH_PRICE:-"http://localhost:5000/hooks/alert-bullish-price"}
    export ALERT_BEARISH_PRICE=${ALERT_BEARISH_PRICE:-"http://localhost:5000/hooks/alert-bearish-price"}
    export ALERT_BULLISH_ALIGNED=${ALERT_BULLISH_ALIGNED:-"http://localhost:5000/hooks/alert-bullish"}
    export ALERT_BEARISH_ALIGNED=${ALERT_BEARISH_ALIGNED:-"http://localhost:5000/hooks/alert-bearish"}
    export ALERT_BULLISH_CROSS=${ALERT_BULLISH_CROSS:-"http://localhost:5000/hooks/alert-bullish"}
    export ALERT_BEARISH_CROSS=${ALERT_BEARISH_CROSS:-"http://localhost:5000/hooks/alert-bearish"}
    echo "> analyzing $TA_EXCHANGE + $TA_MARKET"

    # price above sma 200
    price --timeframe 2h --gt sma 200 \
      && alert --timeframe 2h "price above 2h 200 SMA" --webhook $ALERT_BULLISH_PRICE
    price --timeframe 4h --gt sma 200 \
      && alert --timeframe 4h "price above 4h 200 SMA" --webhook $ALERT_BULLISH_PRICE
    price --timeframe 1d --gt sma 200 \
      && alert --timeframe 1d "price above 1d 200 SMA" --webhook $ALERT_BULLISH_PRICE

    # price below sma 200
    price --timeframe 2h --lt sma 200 \
      && alert --timeframe 2h "price below 2h 200 SMA" --webhook $ALERT_BEARISH_PRICE
    price --timeframe 4h --lt sma 200 \
      && alert --timeframe 4h "price below 4h 200 SMA" --webhook $ALERT_BEARISH_PRICE
    price --timeframe 1d --lt sma 200 \
      && alert --timeframe 1d "price below 1d 200 SMA" --webhook $ALERT_BEARISH_PRICE

    # sma bullish alignment
    aligned --timeframe 1h sma 50 100 200 \
      && alert --timeframe 1h "1h SMA 50 100 200 in bullish alignment" --webhook $ALERT_BULLISH_ALIGNED
    aligned --timeframe 4h sma 50 100 200 \
      && alert --timeframe 4h "4h SMA 50 100 200 in bullish alignment" --webhook $ALERT_BULLISH_ALIGNED
    aligned --timeframe 12h sma 50 100 200 \
      && alert --timeframe 12h "12h SMA 50 100 200 in bullish alignment" --webhook $ALERT_BULLISH_ALIGNED

    # sma bearish alignment
    aligned --timeframe 1h sma 200 100 50 \
      && alert --timeframe 1h "1h SMA 50 100 200 in bearish alignment" --webhook $ALERT_BEARISH_ALIGNED
    aligned --timeframe 4h sma 200 100 50 \
      && alert --timeframe 4h "4h SMA 50 100 200 in bearish alignment" --webhook $ALERT_BEARISH_ALIGNED
    aligned --timeframe 12h sma 200 100 50 \
      && alert --timeframe 12h "12h SMA 50 100 200 in bearish alignment" --webhook $ALERT_BEARISH_ALIGNED

    # golden cross
    aligned --timeframe 2h sma 50 200 \
      && alert --timeframe 2h "2h SMA golden cross" --webhook $ALERT_BULLISH_CROSS
    aligned --timeframe 4h sma 50 200 \
      && alert --timeframe 4h "4h SMA golden cross" --webhook $ALERT_BULLISH_CROSS
    aligned --timeframe 12h sma 50 200 \
      && alert --timeframe 12h "12h SMA golden cross" --webhook $ALERT_BULLISH_CROSS
    aligned --timeframe 1d sma 50 200 \
      && alert --timeframe 1d "1d SMA golden cross" --webhook $ALERT_BULLISH_CROSS

    # death cross
    aligned --timeframe 2h sma 200 50 \
      && alert --timeframe 2h "2h SMA death cross" --webhook $ALERT_BEARISH_CROSS
    aligned --timeframe 4h sma 200 50 \
      && alert --timeframe 4h "4h SMA death cross" --webhook $ALERT_BEARISH_CROSS
    aligned --timeframe 12h sma 200 50 \
      && alert --timeframe 12h "12h SMA death cross" --webhook $ALERT_BEARISH_CROSS
    aligned --timeframe 1d sma 200 50 \
      && alert --timeframe 1d "1d SMA death cross" --webhook $ALERT_BEARISH_CROSS

    # divergence --bullish --timeframe 1d
    # divergence --bullish --timeframe 4h
    # divergence --bearish --timeframe 1d
    # divergence --bearish --timeframe 4h
  )
}

run_extra_alerts() {
  [ -e extra.sh ] && source extra.sh
}

run_all_alerts() {
  echo begin $(date --iso-8601=s)
  for market in $(cat markets) ; do
    run_alerts binance $market
  done
  run_extra_alerts
  echo end $(date --iso-8601=s)
}

# Run periodically
echo "> starting alerts"
run_all_alerts
while sleep 300 ; do
  run_all_alerts
done
