#!/bin/bash

source lib.sh

# $1 exchange
# $2 market
run_alerts() {
  (
    export TA_EXCHANGE=$1
    export TA_MARKET=$2
    export ALERT_BULLISH_PRICE=${ALERT_BULLISH_PRICE:-"http://localhost:5000/hooks/alert-bullish-price"}
    export ALERT_BEARISH_PRICE=${ALERT_BEARISH_PRICE:-"http://localhost:5000/hooks/alert-bearish-price"}
    export ALERT_BULLISH_ALIGNED=${ALERT_BULLISH_ALIGNED:-"http://localhost:5000/hooks/alert-bullish"}
    export ALERT_BEARISH_ALIGNED=${ALERT_BEARISH_ALIGNED:-"http://localhost:5000/hooks/alert-bearish"}
    export ALERT_BULLISH_CROSS=${ALERT_BULLISH_CROSS:-"http://localhost:5000/hooks/alert-bullish"}
    export ALERT_BEARISH_CROSS=${ALERT_BEARISH_CROSS:-"http://localhost:5000/hooks/alert-bearish"}
    echo "> analyzing $TA_EXCHANGE + $TA_MARKET"

    for tf in 1h 2h 4h 12h 1d ; do
      # price above sma 200
      price --timeframe $tf --gt sma 200 \
        && alert --timeframe $tf "price above $tf 200 SMA" --webhook $ALERT_BULLISH_PRICE
      # price below sma 200
      price --timeframe $tf --lt sma 200 \
        && alert --timeframe $tf "price below $tf 200 SMA" --webhook $ALERT_BEARISH_PRICE
      # sma bullish alignment
      aligned --timeframe $tf sma 50 100 200 \
        && alert --timeframe $tf "$tf 50/100/200 SMA in bullish alignment" --webhook $ALERT_BULLISH_ALIGNED
      # sma bearish alignment
      aligned --timeframe $tf sma 200 100 50 \
        && alert --timeframe $tf "$tf 50/100/200 SMA in bearish alignment" --webhook $ALERT_BEARISH_ALIGNED
      # golden cross
      aligned --timeframe $tf sma 50 200 \
        && alert --timeframe $tf "$tf SMA golden cross" --webhook $ALERT_BULLISH_CROSS
      # death cross
      aligned --timeframe $tf sma 200 50 \
        && alert --timeframe $tf "$tf SMA death cross" --webhook $ALERT_BEARISH_CROSS
    done

    # divergence --bullish --timeframe 1d
    # divergence --bearish --timeframe 1d
  )
}

run_extra_alerts() {
  [ -e extra.sh ] && source extra.sh
}

run_all_alerts() {
  echo begin $(date --iso-8601=s)
  for market in $(cat markets) ; do
    run_alerts binance $market
  done
  run_extra_alerts
  echo end $(date --iso-8601=s)
}

# Run periodically
echo "> starting alerts"
run_all_alerts
while sleep 300 ; do
  run_all_alerts
done
